name: Upload Python Package

on:
  workflow_call:

jobs:
  publish-to-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create VERSION file
        run: |
          version=${GITHUB_REF#refs/*/}
          echo "${version//v/}" > version.py
      - name: Check VERSION file
        run: cat version.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --without test,dev
      - name: Publish package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build
